import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useQuery } from '@apollo/client';
import { GET_UNITS } from '../gql/queries/getUnits';

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_UNITS);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className={styles.title}>Units</h1>

      <div>
        {data.units.map(({ id, name }: { id: number; name: string }) => (
          <div key={id}>
            <h3 className={styles.title}>{name}</h3>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
