name: Repo Visualiser
on:
  workflow_dispatch: {}
  push:
    branches:
      - bwekulo/dev
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"